name: Windows - RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Downloading & Installing Essentials
        run: cmd /c Downloads.bat

      - name: Enable RDP and open Port
        run: cmd /c enable_rdp_and_open_port.bat

      - name: Get RDP info
        run: cmd /c get_public_ip.bat

              - name: Setup Tunnel RDP via Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe config add-authtoken $env:NGROK_AUTH_TOKEN
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -WindowStyle Hidden
          Start-Sleep -Seconds 5
          $tunnels = (Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels").tunnels
          $rdpUrl = $tunnels[0].public_url -replace "tcp://", ""
          Write-Output "=========================================="
          Write-Output "ALAMAT RDP KAMU : $rdpUrl"
          Write-Output "USER           : runneradmin"
          Write-Output "=========================================="
        
      - name: Execute anydesk
        shell: pwsh
        run: |
          powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\anydesk_manage.ps1 -Password Awanophile*123

      - name: Keep Alive Loop
        run: cmd /c loop.bat
